### PR TITLE
Fix the social image by passing a full URL for social image

### LINKED ISSUE #20: Social image not appearing correctly
The social images are not appearing correctly. 

image

### PR DESCRIPTION
**Pull request by nsunami**
This PR fixes the social image rendering by passing a full URL, instead of a relative one, for the social image. Fixes #20.

### CODE REVIEW

File: app/core/components/SocialMetadata.tsx [hunk 1]
```diff
@@ -15,6 +15,8 @@ export const SocialMetadata = () => {
       <meta property="og:site_name" content={title} key="ogsitename" />
       <meta property="og:title" content={title} key="ogtitle" />
       <meta property="og:description" content={description} key="ogdesc" />
+      {/* Twittter */}
+      <meta name="twitter:card" content="summary_large_image" />
```
Comment (nsunami) [inline app/core/components/SocialMetadata.tsx:19]: I ended up removing all the twitter-specific metatags, expect the one for `tiwtter:card` here
